# This is an example/template for and ETL dataset configuration
# It is designed to represent the data provenance of data extracted
# from and source out in the wild, transformed, and then loaded
# into your controlled data storage (e.g. blob storage).
# Datasets extracted from uncontrolled sources should be
# considered unstable and subject to change without notice.
# Thus, it is recommended to store the raw extracted data
# as well as the transformed data in your controlled storage.
# This example uses a CDC data source, but you can use any
# publicly available data source. any value in curly braces {}
# should be replaced with your own values as needed.

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "{python_compatible_name}"
automate = false
transform_template = "{location for any sql applied to reference data}"
schema = "{namespace for schema}"
type = "etl"

############################################################################

[source]
# These source fields are open to being changed based on the source type
# and api requirements. This example uses a Socrata data source
# which is common for CDC data sources.

url = "https://data.cdc.gov/resource/{data_uid}.csv"
pagination = {limit = 50000}

############################################################################

[extract]
# These are the details of where to store the raw extracted data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/{group_user_or_repo_name}/raw/{dataset_name}"

############################################################################

[load]
# These are the details of where to store the transformed and loaded data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/{group_user_or_repo_name}/transformed/{dataset_name}"

############################################################################

# Changelog
# ---------
# 2025-09-08: Initial version created by Phil Rogers
