# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/Laboratory-Surveillance/SARS-CoV-2-Variant-Proportions/jr58-6ysp/data_preview
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]
name = "sars_cov2_proportions"
automate = false
transform_template = "scenarios/sars_cov2_proportions.sql"
schema = "datasets/scenarios/schemas/sars_cov2_proportions.py"

[source]
url = "https://data.cdc.gov/resource/jr58-6ysp.csv"
pagination = {limit = 1000}

[extract]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/sars_cov2_proportions"

[load]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/sars_cov2_proportions"

# TODO: add some data schema validation
