# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/Vaccinations/COVID-19-Vaccination-Age-and-Sex-Trends-in-the-Uni/5i5k-6cmh/data_preview
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]

name = "respnet"
automate = false
transform_template = ""
schema = ""

[source]

domain = "data.cdc.gov"
id = "kvib-3txy"
limit = 10000

[extract]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/mcmv/raw/respnet"

[load]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/mcmv/transformed/respnet"

# TODO: add some data schema validation
