# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/Vaccinations/COVID-19-Vaccination-Age-and-Sex-Trends-in-the-Uni/5i5k-6cmh/data_preview
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]

name = "covid19vax_trends"
automate = false
transform_template = "covid19vax_trends.sql"
schema = "datasets/schemas/covid19vax_trends.py"

[source]

url = "https://data.cdc.gov/resource/5i5k-6cmh.csv"
pagination = {limit = 50000}

[extract]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/covid19vax_trends"

[load]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/covid19vax_trends"

# TODO: add some data schema validation
