# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/Vaccinations/Weekly-Cumulative-COVID-19-Vaccination-Coverage-an/ksfb-ug5d/about_data
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]

name = "covid19_vax_coverage_adult"
automate = false
transform_template = "covid19_vax_coverage_adult.sql"
schema = "datasets/schemas/covid19_vax_coverage_adult.py"

[source]

url = "https://data.cdc.gov/resource/ksfb-ug5d.csv"
pagination = {limit = 1000}

[extract]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/covid19_vax_coverage_adult"

[load]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/covid19_vax_coverage_adult"

# TODO: add some data schema validation
