# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/sgxm-t72h/data_preview
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]
name = "covid19hospitalizations"
automate = false
transform_template = "covid19hospitalizations.sql"

[source]
url = "https://healthdata.gov/resource/sgxm-t72h.csv"
pagination = {limit = 1000}

[extract]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/covid19hospitalizations"

[load]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/covid19hospitalizations"

# TODO: add some data schema validation
