# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/Laboratory-Surveillance/2022-2023-Nationwide-Blood-Donor-Seroprevalence-Su/ar8q-3jhn/data_preview
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]
name = "donor_seroprevalence_2022"
automate = false
transform_template = "donor_seroprevalence_2022.sql"

[source]
url = "https://data.cdc.gov/resource/ar8q-3jhn.csv"
pagination = {limit = 1000}

[extract]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/donor_seroprevalence_2022"

[load]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/donor_seroprevalence_2022"

# TODO: add some data schema validation