# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.transportation.gov/resource/eek5-pv8d.csv
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]
name = "fips_to_name"
automate = false
transform_template = "fips_to_name.sql"

[source]
url = "https://data.transportation.gov/resource/eek5-pv8d.csv"
pagination = {limit = 1000}

[extract]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/fips_to_name"

[load]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/fips_to_name"
