# This dataset is static, and thus only needs to be extracted in it's raw form
# once and saved to blob storage. For a human viewable we format, see:
# https://data.cdc.gov/resource/aemt-mg7g.csv
# Raw (extracted) and transformed (loaded) data will be stored in azure blob storage
# which requires the account, container and path for access

[properties]

name = "hospitalization"
automate = false
transform_template = "hospitalization.sql"
schema = "hospitalization.py"

[source]

url = "https://data.cdc.gov/resource/aemt-mg7g.csv"
pagination = {limit = 1000}

[extract]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/hospitalization"

[load]

account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/hospitalization"

# TODO: add some data schema validation
