# This dataset is static and taken from github.com/cdcent/cfa-scenarios-initialization
# data will be stored in azure blob storage

[properties]
name = "us_age_distribution"
automate = false
transform_template = ""

[source]
url = ""
pagination = {limit = 1000}

[extract]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/raw/us_age_distribution"

[load]
account = "cfadatalakeprd"
container = "cfapredict"
prefix = "dataops/scenarios/transformed/us_age_distribution"

# TODO: add some data schema validation
