name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up poetry
        uses: ./.github/actions/setup-poetry

      - name: Test
        run: poetry run pytest
