name: Build Release Distribution

on:
  push:
    tags:
      # below is same as ^\d{4}\.\d{2}\.\d{2}$ seems workflows use simpler regex
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9]+'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install Dependencies
        run: |
          poetry install --no-root

      - name: Build Wheel
        run: |
          poetry build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} dist/* --generate-notes --latest

      - name: Update pyproject Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}

          sed -i.bak -E "s/^version\s*=\s*\"[^\"]+\"/version = \"${VERSION}\"/" pyproject.toml

      - name: Update Change Log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          REPO_URL="https://github.com/${{ github.repository }}"
          RELEASE_URL="$REPO_URL/releases/tag/$VERSION"

          awk -v tag="## [$VERSION]" -v url="$RELEASE_URL" '
            !done && /---/ {
              print ""
              print tag
              print url
              print ""
              done = 1
              }
              { print $0 }
            ' changelog.md > temp.md && mv temp.md changelog.md
