name: Build Release Distribution

on:
  push:
    tags:
      - '*r'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
      
      - name: Install Dependencies
        run: |
          poetry install --no-root
      
      - name: Build Wheel
        run: |
          poetry build
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} dist/* --latest

      - name: Check if Release Exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          retries=5
          for i in $(seq 1 $retries); do
            if gh release view ${{ github.ref }}; then
              echo "Release Found, Proceeding to Update Notes"
              break
            fi
            echo "Release Not Found, Retrying in 5 Seconds"
            sleep 5
          done

      - name: Generate and Update Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ github.ref }} --json body --jq '.body' >> changelog.md
          gh release edit ${{ github.ref }} --notes-file changelog.md